//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoshakBioSciences.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MenuMaster
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public string SubMenu { get; set; }
        public string Url { get; set; }
        public string AltTag { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    }
}
