//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoshakBioSciences.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoshBioSolDbEntities : DbContext
    {
        public PoshBioSolDbEntities()
            : base("name=PoshBioSolDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_MasterTable> M_MasterTable { get; set; }
        public virtual DbSet<M_MenuMaster> M_MenuMaster { get; set; }
        public virtual DbSet<M_ProductMaster> M_ProductMaster { get; set; }
    }
}
